export const COMMIT_TYPES = {
    feat: {
        emoji: "✨",
        descriptionEsp: "Agregar nueva característica",
        description: "Add new feature",
        release: true,
        color: "green",
    },
    fix: {
        emoji: "🐛",
        descriptionEsp: "Corregir error",
        description: "Fix bug",
        release: true,
        color: "red",
    },
    perf: {
        emoji: "⚡",
        descriptionEsp: "Mejora rendimiento",
        description: "Improve performance",
        release: true,
        color: "yellow",
    },
    style: {
        emoji: "💎",
        descriptionEsp: "Cambio de estilo",
        description: "Style change",
        release: true,
        color: "magenta",
    },
    refactor: {
        emoji: "💅",
        descriptionEsp: "Refactorizar código",
        description: "Refactor code",
        release: true,
        color: "blue",
    },
    docs: {
        emoji: "📚",
        descriptionEsp: "Agregar o actualizar documentación",
        description: "Add or update documentation",
        release: false,
        color: "white",
    },
    test: {
        emoji: "\uD83D\uDEA8",
        descriptionEsp: "Agregar o actualizar tests",
        description: "Add or update tests",
        release: false,
        color: "yellow",
    },
    build: {
        emoji: "\uD83D\uDEE0 ",
        descriptionEsp: "Agregar o actualizar build scripts",
        description: "Add or update build scripts",
        release: false,
        color: "dim",
    },
};
